package interpreter;

public enum TokenTypes {

    LEFT_PARAM, RIGHT_PARAM, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT , MINUS, PLUS, SEMICOLON, SLASH, STAR , MODULUS, POWER,

    BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,

    IDENTIFIER, STRING, NUMBER,

    AND,CLASS,ELSE,FALSE,FUNCTION,FOR,IF,NIL,OR,PRINT,RETURN,SUPER,THIS,TRUE,VAR,WHILE,

    EOF

}
